#!/usr/bin/env python
"""PreToolUse guard for the Home Assistant config on H:.

Enforces two CLAUDE.md CONSTRAINTS mechanically instead of by comment, because
a comment at the top of a file is advice and a hook is a wall:

  1. ENTITIES.md / AUTOMATIONS.md / PACKAGES.md are GENERATED. Hand-editing
     them is how a wrong entity id gets into the one document CONSTRAINTS calls
     the only permitted source of ids.
  2. .storage/* is HA-managed JSON. Editing it corrupts dashboards
     unrecoverably.

SCOPED TO THE HA CONFIG. A file called ENTITIES.md in some unrelated project is
none of this hook's business, so the path must resolve under H: (or the
//10.0.0.210/config UNC that H: maps to). Over-blocking would train the user to
disable the hook, which costs more than it saves.

jq is not installed on this machine, so this is Python rather than the usual
jq one-liner.

Exits 0 always. Silence = allow.
"""
import json
import os
import sys

GENERATED = {"entities.md", "automations.md", "packages.md"}


def main():
    try:
        payload = json.load(sys.stdin)
    except (ValueError, OSError):
        return  # never block on a payload we cannot read

    ti = payload.get("tool_input") or {}
    path = ti.get("file_path") or ti.get("notebook_path") or ""
    if not isinstance(path, str) or not path:
        return

    norm = path.replace("\\", "/").lower()

    # Only police the HA config tree.
    in_ha = (norm.startswith("h:/") or norm.startswith("/h/")
             or "10.0.0.210/config" in norm)
    if not in_ha:
        return

    base = os.path.basename(norm)
    reason = None

    if base in GENERATED:
        reason = (
            "BLOCKED: %s is GENERATED by scripts/gen_reference.py and must "
            "never be hand-edited. A hand-edited entry is CLAUDE.md "
            "instructing you to use a name that resolves to unknown. "
            "To change an annotation edit entity_notes.yaml, then run:\n"
            "  HA_CONFIG='H:/' python H:/scripts/gen_reference.py"
            % os.path.basename(path)
        )
    elif "/dashboards/lovelace/" in norm:
        reason = (
            "BLOCKED: dashboards/lovelace/* is GENERATED by "
            "scripts/export_dashboards.py - a mirror of the LIVE dashboards and "
            "the only backup of .storage/lovelace.*, which is gitignored and "
            "off-limits to edit. Hand-editing the mirror gives you a backup that "
            "no longer matches what HA renders, which is worse than no backup. "
            "To change a dashboard: edit dashboards/views/, hand the user the "
            "YAML to paste into the raw configuration editor, then re-run:\n"
            "  HA_CONFIG='H:/' python H:/scripts/export_dashboards.py"
        )
    elif "/.storage/" in norm or norm.endswith("/.storage"):
        reason = (
            "BLOCKED: .storage/* is HA-managed JSON. CLAUDE.md CONSTRAINTS: "
            "NEVER edit .storage/* - corrupts dashboards unrecoverably. "
            "Dashboards are changed by handing the user YAML to paste into the "
            "raw configuration editor; reading .storage is fine, writing is not."
        )

    if reason:
        json.dump({"hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }}, sys.stdout)


if __name__ == "__main__":
    main()
