#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export every live Lovelace dashboard from .storage to dashboards/lovelace/.

WHY THIS EXISTS. The live dashboards are UI-managed and live only in
.storage/lovelace.*, which is correctly off-limits to edit and is excluded from
git by .gitignore. That means the single most laborious artifact in this config
-- 16 views across 4 dashboards, thousands of lines of hand-tuned cards -- had
NO backup and NO version history at all. A .storage corruption or a bad "start
over" in the UI editor loses all of it with nothing to restore from.

WHAT IT WRITES. One file per dashboard, holding the COMPLETE config, because
that is the unit HA's raw configuration editor accepts: open the dashboard,
three-dot menu > Raw configuration editor, select all, paste. Plus the
dashboard registry and the resource list, which are what tell you WHICH
dashboards should exist and which custom cards they need.

THESE ARE GENERATED. Do not hand-edit them - the next run overwrites. They are
a MIRROR OF WHAT IS DEPLOYED, not a source you edit and push.

  dashboards/lovelace/   GENERATED. What is live right now. Restore from here.
  dashboards/views/      HAND-MAINTAINED working copies. May be deliberately
                         AHEAD of live, holding corrections not yet pasted in.
                         dehumidifier.yaml is exactly that as of 2026-08-24.

Not the same thing, and not an R10 duplicate: one records deployed state, the
other holds pending work. If they agree, the work has been pasted.

NOTHING CHECKS THESE FOR STALENESS. ha_audit.py does not know about them, so a
UI edit made after the last run leaves this mirror silently behind. Re-run it
after changing a dashboard. Said plainly because an unchecked file that looks
generated invites the assumption that something is watching it (R8).

Usage:  HA_CONFIG='H:/' python scripts/export_dashboards.py
"""
import io
import json
import os
import sys
import glob

CONFIG = os.environ.get("HA_CONFIG", "/config")
P = lambda *a: os.path.join(CONFIG, *a)
SKIP = ("lovelace_dashboards", "lovelace_resources")


# Strings a YAML 1.1 parser coerces to bool/null and PyYAML does NOT.
#
# 2026-08-24, EARNED THE HARD WAY. apexcharts annotations use the key `y`.
# PyYAML's bool resolver matches yes|no|true|false|on|off but NOT bare `y`, so
# it emits `y: 60` unquoted and reads it straight back as the string "y" - a
# clean round-trip that proves nothing. Home Assistant's FRONTEND parses the
# raw configuration editor with js-yaml on a YAML 1.1 bool set, where `y` IS
# true. Pasting such YAML rewrote five annotation keys in
# .storage/lovelace.lovelace as the literal string "true", silently killing the
# 60 % mold-ceiling line and four zero lines on the live dehumidifier view.
#
# Round-tripping through the same library you dumped with is not a test. The
# parser that matters is the one that CONSUMES the file (R6). Quote anything
# either dialect could reinterpret.
_AMBIGUOUS = frozenset("""
y Y yes Yes YES n N no No NO true True TRUE false False FALSE on On ON off Off
OFF ~ null Null NULL
""".split())


def _yaml():
    import yaml

    def block(dumper, data):
        if "\n" in data:
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
        if data in _AMBIGUOUS:
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="'")
        return dumper.represent_scalar("tag:yaml.org,2002:str", data)

    yaml.add_representer(str, block)
    return yaml


def header(src, extra=""):
    return ("# GENERATED by scripts/export_dashboards.py - DO NOT HAND-EDIT.\n"
            "# Source: .storage/%s (UI-managed; HA loads that, never this file).\n"
            "# Restore: dashboard > three-dot menu > Raw configuration editor,\n"
            "#          select all, replace with everything below this header.\n"
            "%s#\n" % (src, extra))


def main():
    yaml = _yaml()
    out_dir = P("dashboards", "lovelace")
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)

    written = []
    for path in sorted(glob.glob(P(".storage", "lovelace*"))):
        base = os.path.basename(path)
        try:
            with io.open(path, encoding="utf-8") as fh:
                blob = json.load(fh)
        except (IOError, OSError, ValueError) as exc:
            print("  SKIP %s (%s)" % (base, exc))
            continue

        if base in SKIP:
            data = blob.get("data", {})
            name = "_" + base.replace("lovelace_", "") + ".yaml"
            body = header(base, "# This is a REGISTRY, not a dashboard: it records which dashboards\n"
                                "# exist / which custom card resources load. Not pasteable.\n")
            n = len(data.get("items", []))
        else:
            cfg = blob.get("data", {}).get("config")
            if cfg is None:
                print("  SKIP %s (no config)" % base)
                continue
            key = base[len("lovelace."):] if base.startswith("lovelace.") else base
            name = key + ".yaml"
            data = cfg
            n = len(cfg.get("views", []))
            body = header(base, "# %d view(s).\n" % n)

        text = body + yaml.dump(data, allow_unicode=True, sort_keys=False,
                                default_flow_style=False, width=100)
        with io.open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        written.append((name, n, len(text)))

    print("wrote %d file(s) to dashboards/lovelace/" % len(written))
    for name, n, size in written:
        print("   %-28s %2d item(s)  %6d bytes" % (name, n, size))
    return 0


if __name__ == "__main__":
    sys.exit(main())
